version: '3.8'
name: weather-collector-docker-compose
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./prod.env

  worker:
    build: .
    stdin_open: true
    tty: true
    restart: on-failure
    depends_on:
      - db
    env_file:
      - ./prod.env

volumes:
  postgres: