version: '3.8'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./prod.env

  worker:
    build: .
    restart: on-failure
    depends_on:
      # [FIXME] helthcheck
      # This service starting running after previous has been mounted,
      # but not after it has done its execution.
      - db
    # env_file:
    #   - ./prod.env
